# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  authentication:
    class: AppBundle\Service\Authentication
    arguments: ['@instagram_interface']

  instagram_interface:
    class: AppBundle\Service\InstagramInterface
    arguments: ['%instagram%']

  inspiration_board:
    class: AppBundle\Service\InspirationBoard
    arguments: ['@instagram_interface']

  curl_wrapper:
    class: AppBundle\Service\CurlWrapper
